-- Copyright 2024 Logan Magee
--
-- SPDX-License-Identifier: AGPL-3.0-only

-- Create the listings table
--
-- Generated by Exposed 0.48.0 from the original Listings.kt
CREATE TABLE listings (id INTEGER PRIMARY KEY AUTOINCREMENT, app_id TEXT NOT NULL, locale TEXT NOT NULL, label TEXT NOT NULL, CONSTRAINT fk_listings_app_id__id FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE UNIQUE INDEX listings_app_id_locale ON listings (app_id, locale);

-- Create a default listing for each published app
INSERT INTO listings (app_id, locale, label) SELECT id, 'en-US', label FROM apps;

-- Delete the obsolete label column from the apps table
ALTER TABLE apps DROP COLUMN label;
