# SPDX-FileCopyrightText: © 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

# General application configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=17
quarkus.datasource.jdbc.transaction-isolation-level=serializable
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-at-start=true
quarkus.flyway.validate-migration-naming=true
quarkus.generate-code.grpc.scan-for-imports=com.google.protobuf:protobuf-java,build.buf:protovalidate,com.google.api.grpc:proto-google-common-protos
quarkus.grpc.server.use-separate-server=false
quarkus.mailer.tls=true
quarkus.native.additional-build-args=--initialize-at-run-time=app.accrescent.server.parcelo.security.Identifier\\,app.accrescent.server.parcelo.security.IpAddressSaltService
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.cookie-force-secure=true
quarkus.oidc.authentication.cookie-same-site=strict
quarkus.quartz.clustered=true
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.table-prefix=quartz_

# Development and testing configuration
%dev,test,it.parcelo.admin.oidc-provider=local
%dev,test,it.parcelo.admin.oidc-subject=c54374b4-b1f6-4d4b-8cb9-d6cfea172a58
%dev,test,it.parcelo.buckets.app-package=apppackage
%dev,test,it.parcelo.buckets.app-upload=appupload
%dev,test,it.parcelo.buckets.draft-listing-icon-upload=draftlistingiconupload
%dev,test,it.parcelo.buckets.edit-upload=editupload
%dev,test,it.parcelo.buckets.edit-listing-icon-upload=editlistingiconupload
%dev,test,it.parcelo.buckets.listing-image=listingimage
%dev,test,it.parcelo.buckets.published-artifact=appartifacts
%dev,test,it.parcelo.artifacts-base-url=http://localhost:8080
%dev,test,it.parcelo.file-processing-directory=/tmp
%dev,test,it.parcelo.object-storage-notifications.app-draft-uploads.pubsub-project-id=dev-project
%dev,test,it.parcelo.object-storage-notifications.app-draft-uploads.pubsub-subscription-name=parcelo-adu
%dev,test,it.parcelo.object-storage-notifications.app-draft-listing-icon-uploads.pubsub-project-id=dev-project
%dev,test,it.parcelo.object-storage-notifications.app-draft-listing-icon-uploads.pubsub-subscription-name=parcelo-adliu
%dev,test,it.parcelo.object-storage-notifications.app-edit-uploads.pubsub-project-id=dev-project
%dev,test,it.parcelo.object-storage-notifications.app-edit-uploads.pubsub-subscription-name=parcelo-aeu
%dev,test,it.parcelo.object-storage-notifications.app-edit-listing-icon-uploads.pubsub-project-id=dev-project
%dev,test,it.parcelo.object-storage-notifications.app-edit-listing-icon-uploads.pubsub-subscription-name=parcelo-aeliu
%dev,test,it.parcelo.rate-limiting.buckets.authenticated.version=0
%dev,test,it.parcelo.rate-limiting.buckets.authenticated.limits.long-term.period=1h
%dev,test,it.parcelo.rate-limiting.buckets.authenticated.limits.long-term.requests=1000
%dev,test,it.parcelo.rate-limiting.buckets.authenticated.limits.short-term.period=1s
%dev,test,it.parcelo.rate-limiting.buckets.authenticated.limits.short-term.requests=10
%dev,test,it.parcelo.rate-limiting.buckets.unauthenticated.version=0
%dev,test,it.parcelo.rate-limiting.buckets.unauthenticated.limits.default.period=1h
%dev,test,it.parcelo.rate-limiting.buckets.unauthenticated.limits.default.requests=60
%dev,test,it.parcelo.rate-limiting.buckets.upload-apis.version=0
%dev,test,it.parcelo.rate-limiting.buckets.upload-apis.limits.default.period=1h
%dev,test,it.parcelo.rate-limiting.buckets.upload-apis.limits.default.requests=30
%dev,test,it.quarkus.flyway.clean-at-start=true
%dev,test,it.quarkus.flyway.validate-at-start=false
%dev,test,it.quarkus.google.cloud.pubsub.devservices.project-id=dev-project
%dev,test,it.quarkus.google.cloud.pubsub.devservices.topics.apk-set-uploaded.subscription-names=parcelo-adu
%dev,test,it.quarkus.google.cloud.pubsub.devservices.topics.draft-icon-uploaded.subscription-names=parcelo-adliu
%dev,test,it.quarkus.google.cloud.pubsub.devservices.topics.app-edit-uploaded.subscription-names=parcelo-aeu
%dev,test,it.quarkus.google.cloud.pubsub.devservices.topics.edit-icon-uploaded.subscription-names=parcelo-aeliu
%dev,test,it.quarkus.google.cloud.storage.devservices.buckets=appupload,apppackage,draftlistingiconupload,editupload,editlistingiconupload,listingimage
# Overridden until similar functionality exists upstream. See
# https://github.com/fsouza/fake-gcs-server/pull/2135.
%dev,test,it.quarkus.google.cloud.storage.devservices.image-name=accrescent/fake-gcs-server:multiple-event-configs
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[0].bucket=appupload
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[0].pubsub-project-id=dev-project
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[0].pubsub-topic=apk-set-uploaded
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[1].bucket=draftlistingiconupload
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[1].pubsub-project-id=dev-project
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[1].pubsub-topic=draft-icon-uploaded
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[2].bucket=editupload
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[2].pubsub-project-id=dev-project
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[2].pubsub-topic=app-edit-uploaded
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[3].bucket=editlistingiconupload
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[3].pubsub-project-id=dev-project
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications[3].pubsub-topic=edit-icon-uploaded
# Keycloak OOMs with the default memory limit
%dev,test,it.quarkus.keycloak.devservices.container-memory-limit=2G
%dev,test,it.quarkus.keycloak.devservices.realm-path=quarkus-realm.json
%dev,test,it.quarkus.mailer.mock=true
%dev,test,it.quarkus.minio.devservices.buckets=appartifacts
quarkus.test.integration-test-profile=it
