# SPDX-FileCopyrightText: © 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

# General application configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=17
quarkus.datasource.jdbc.transaction-isolation-level=serializable
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-at-start=true
quarkus.flyway.validate-migration-naming=true
quarkus.generate-code.grpc.scan-for-imports=com.google.protobuf:protobuf-java,build.buf:protovalidate,com.google.api.grpc:proto-google-common-protos
quarkus.grpc.server.use-separate-server=false
quarkus.mailer.tls=true
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.cookie-force-secure=true
quarkus.oidc.authentication.cookie-same-site=strict
quarkus.quartz.clustered=true
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.table-prefix=quartz_

# Development and testing configuration
%dev,test,it.parcelo.admin.oidc-provider=local
%dev,test,it.parcelo.admin.oidc-subject=c54374b4-b1f6-4d4b-8cb9-d6cfea172a58
%dev,test,it.parcelo.app-package-bucket=apppackage
%dev,test,it.parcelo.app-upload-bucket=appupload
%dev,test,it.parcelo.artifacts-base-url=http://localhost:8080
%dev,test,it.parcelo.image-upload-service-base-url=http://${quarkus.http.host}:${quarkus.http.port}
%dev,test,it.parcelo.listing-image-bucket=listingimage
%dev,test,it.parcelo.package-processing-directory=/tmp
%dev,test,it.parcelo.published-artifact-bucket=appartifacts
%dev,test,it.parcelo.pubsub.project-id=dev-project
%dev,test,it.parcelo.pubsub.subscription-name=parcelo
%dev,test,it.parcelo.rate-limits.authenticated.version=0
%dev,test,it.parcelo.rate-limits.authenticated.limits.long-term.period=1h
%dev,test,it.parcelo.rate-limits.authenticated.limits.long-term.requests=1000
%dev,test,it.parcelo.rate-limits.authenticated.limits.short-term.period=1s
%dev,test,it.parcelo.rate-limits.authenticated.limits.short-term.requests=10
%dev,test,it.parcelo.rate-limits.unauthenticated.version=0
%dev,test,it.parcelo.rate-limits.unauthenticated.limits.default.period=1h
%dev,test,it.parcelo.rate-limits.unauthenticated.limits.default.requests=60
%dev,test,it.parcelo.rate-limits.upload-apis.version=0
%dev,test,it.parcelo.rate-limits.upload-apis.limits.default.period=1h
%dev,test,it.parcelo.rate-limits.upload-apis.limits.default.requests=30
%dev,test,it.quarkus.flyway.clean-at-start=true
%dev,test,it.quarkus.flyway.validate-at-start=false
%dev,test,it.quarkus.google.cloud.pubsub.devservices.project-id=dev-project
%dev,test,it.quarkus.google.cloud.pubsub.devservices.topics.apk-set-uploaded.subscription-names=parcelo
%dev,test,it.quarkus.google.cloud.storage.devservices.buckets=appupload,apppackage,listingimage
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications.bucket=appupload
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications.pubsub-project-id=dev-project
%dev,test,it.quarkus.google.cloud.storage.devservices.notifications.pubsub-topic=apk-set-uploaded
# Keycloak OOMs with the default memory limit
%dev,test,it.quarkus.keycloak.devservices.container-memory-limit=2G
%dev,test,it.quarkus.keycloak.devservices.realm-path=quarkus-realm.json
%dev,test,it.quarkus.mailer.mock=true
%dev,test,it.quarkus.minio.devservices.buckets=appartifacts
quarkus.test.integration-test-profile=it
