# SPDX-FileCopyrightText: © 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

parcelo.app-package-bucket=apppackage
parcelo.app-upload-bucket=appupload
parcelo.package-processing-directory=/tmp
parcelo.published-artifact-bucket=appartifacts
parcelo.pubsub.project-id=dev-project
parcelo.pubsub.subscription-name=parcelo
quarkus.google.cloud.pubsub.devservices.project-id=dev-project
quarkus.google.cloud.pubsub.devservices.topics.apk-set-uploaded.subscription-names=parcelo
quarkus.google.cloud.storage.devservices.buckets=appupload,apppackage
quarkus.google.cloud.storage.devservices.notifications.bucket=appupload
quarkus.google.cloud.storage.devservices.notifications.pubsub-project-id=dev-project
quarkus.google.cloud.storage.devservices.notifications.pubsub-topic=apk-set-uploaded
quarkus.minio.devservices.buckets=appartifacts
