# SPDX-FileCopyrightText: © 2026 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

parcelo:
  DirectPreparedStatementExecuteUpdate:
    active: true
  JavaBase64Usage:
    active: true
  TruncatingIntegerConversion:
    active: true
  UnsafeJdbcResultSetMethodCall:
    active: true
  UnusedEitherValue:
    active: true
