# Copyright 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Build & push Parcelo Docker image

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/metadata-action@v5
        with:
          images: accrescent/parcelo
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
